### ISSUE TITLE
start-stop-daemon: issues with lxc containers

### ISSUE THREAD

**Issue by alexxy** [OpenRC/openrc#176] opened 2017-10-31 21:21 UTC
If you start containers at boot using openrc on runlevel default, and containers may have services such as openssd vixie-cron and null-mailer, and at the same time host have such services, then host version of this services wouldnt start because they will see container ones in process tree.

Gentoo-Bug: [634004](https://bugs.gentoo.org/634004)

**Comment by williamh** [comment] 2017-10-31 23:38
Since this is a duplicate of a gentoo bug, please close the gentoo bug.

Also, please test with openrc-0.34.5 and let me know if the issue still exists.

Thanks,

William

**Comment by alexxy** [comment] 2017-11-01 21:48
Seems like it fixed in 0.34.5

**Comment by williamh** [comment] 2017-11-28 19:02
Ok, thanks.

**Closed by williamh** 2017-11-28 19:02 UTC
