### ISSUE TITLE
Directory support for /etc/conf.d/modules?

### ISSUE THREAD

**Issue by simonvanderveldt** [OpenRC/openrc#130] opened 2017-05-06 11:49 UTC
Would it be possible to support `/etc/conf.d/modules` being a directory so it can be used with multiple files inside that directory declaring the modules to load vs just the single file it is now?

**Comment by benkohler** [comment] 2017-06-01 18:07
I think you may be looking for /etc/modules-load.d/ which (along with a few other paths) is parsed by the /etc/init.d/modules-load service, does that take care of what you need?

**Comment by simonvanderveldt** [comment] 2017-06-01 20:18
@benkohler Thanks for the pointer. That location doesn't "sound" like an OpenRC config location though, are you sure that's correct :?
I do have a `modules-load` service, but also a `modules` service, not really sure why we now have two.
I guess `modules-load` would then do what you described, whilst `modules` uses `/etc/conf.d/modules`?

**Comment by benkohler** [comment] 2017-06-01 21:22
It's to mimic systemd behavior (don't let this turn you off though)... so upstream packages shipping module load files for other major distros will also work as intended on gentoo.  But it's very useful for gentoo end-users as well.

**Comment by benkohler** [comment] 2017-06-01 21:23
All occurences of "gentoo" in the previous comment should be replaced by "OpenRC" =) my mistake

**Comment by williamh** [comment] 2017-06-02 15:23
@benkohler is correct about why we have modules-load and modules.
@simonvanderveldt Yes, you should be able to use /etc/modules-load.d to get what you want. I'm closing this issue, but feel free to add a comment if you need help with how to set this up.
Basically, you meed to list the modules you want to load, one per line, in a file in /etc/modules-load.d.

**Closed by williamh** 2017-06-02 15:23 UTC

**Comment by simonvanderveldt** [comment] 2017-09-23 14:22
@williamh @benkohler A bit late (sorry about that), but it seems like modules listed in files inside `/etc/modules-load.d` don't support passing arguments (nor marking them for specific kernel versions or giving them a different name), like one can do for modules listed in `/etc/conf.d/modules`, is that correct?
