### ISSUE TITLE
supervise-daemon uses 100% cpu with version 0.40

### ISSUE THREAD

**Issue by cimarronline** [OpenRC/openrc#264] opened 2018-12-04 14:42 UTC
With openrc 0.40 I'm seeing 100% cpu usage from six agetty processes ("supervise-daemon agetty..."). No errors in rc.log or rc-status. Version 0.39.2 worked fine. The agetty init script is:

```
#!/usr/bin/openrc-run
# Copyright (c) 2017 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
# except according to the terms contained in the LICENSE file.

description="start agetty on a terminal line"
supervisor=supervise-daemon
port="${RC_SVCNAME#*.}"
term_type="${term_type:-linux}"
command=/sbin/agetty
command_args_foreground="${agetty_options} ${port} ${baud} ${term_type}"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	after local
	keyword -prefix
}

start_pre() {
	if [ -z "$port" ]; then
		eerror "${RC_SVCNAME} cannot be started directly. You must create"
		eerror "symbolic links to it for the ports you want to start"
		eerror "agetty on and add those to the appropriate runlevels."
		return 1
	else
		export EINFO_QUIET="${quiet:-yes}"
	fi
}

stop_pre()
{
	export EINFO_QUIET="${quiet:-yes}"
}

```

**Comment by E5ten** [comment] 2018-12-04 20:23
I didn't check exactly which services they were but I saw multiple supervise-daemon processes using a ton of CPU and I don't think they were all agetty instances (they might have been but I think I recall seeing others) I've since downgraded back to 0.39.2 which has no issue.

**Comment by williamh** [comment] 2018-12-05 03:06
What posix function should be used in the supervisor main loop to sleep until there is activity on the fifo or until a signal is received? I know select is one way to do this, but I don't know how signals interact with it.

**Comment by williamh** [comment] 2018-12-05 03:14
The issue is in the supervisor main loop in supervise-daemon.c. I'm not sure how to coordinate the waitpid() call with reading the fifo which happens just below it.

**Comment by williamh** [comment] 2018-12-05 16:19
I am looking into resolving this by using the poll() function.

**Comment by williamh** [comment] 2018-12-06 00:17
It looks like I will be able to do this with blocking fifos and not worry about using poll(). I will test on another system tonight.

**Closed** 2018-12-06 22:42 UTC

**Comment by cimarronline** [comment] 2018-12-07 00:08
Works great. Thank you for the quick fix.
